pcm.!default {
    type pipewire
    playback_node "MicYouVirtualSink"
    capture_node "-1"
    hint {
        show on
        description "MicYou PipeWire virtual sink"
    }
}

ctl.!default {
    type pipewire
}
